### ISSUE TITLE
Lua config doesn't seem to execute commands with exec_once as autoload

### ISSUE THREAD

**Issue by vnepogodin** [pinnacle-comp/pinnacle#121]
Lua config doesn't seem to execute commands with `exec_once` as autoload, while `exec` works fine

e.g
```lua
process.spawn_once("alacritty", function(stdout, stderr, exit_code, exit_msg)
   print("finished spawn_once")
end)
```

alacritty doesn't show up after launch.

**Comment by Ottatop** [comment]
If you have alacritty open anywhere else on your system then Pinnacle counts it as running and won't spawn it using `spawn_once`.

The solution would be to check if the program was spawned by Pinnacle itself before choosing not to run it.

**Comment by Ottatop** [comment]
Should be fixed now, feel free to reopen if it still doesn't work.
