### ISSUE TITLE
Add window raising to API and use in toggle floating/maximized

### ISSUE THREAD

**Issue by Ottatop** [pinnacle-comp/pinnacle#179]

**Comment by ildar** [comment]
AFAIR awesomewm also doesn't raise windows. But you can do that in the
keybinding.
Except fullscreen mode: the window is supposed to go to the top layer
(through layer-shell).

**Comment by Ottatop** [comment]
A very good point, did not realize that

**Comment by Ottatop** [comment]
Implemented in 0ae090b
