### ISSUE TITLE
Allow running Pinnacle without xwayland

### ISSUE THREAD

**Issue by LogicalOverflow** [pinnacle-comp/pinnacle#222]
Both helpful for simplifying the wlcs tests, see #204 for context, and also a feature someone could actually want

I am mostly think having a CLI flag for this. A feature flag, in addition to the CLI flag, to allow compiling without depending on xwayland, might also be coo later on, but l wouldn't consider it part of this issue.

**Comment by Ottatop** [comment]
Implemented in b654de8

I experimented with a feature flag but it only removed a whopping one dependency from building, so I deemed it unnecessary. Also xwayland is a runtime dependency so there's even less need for a feature flag.
