### ISSUE TITLE
Modularize `start_config` to avoid duplication for `wlcs` tests

### ISSUE THREAD

**Issue by LogicalOverflow** [pinnacle-comp/pinnacle#223]
Currently, the config for `wlcs` tests is started with its own start function, to allow passing in a closure and to skip starting xwayland. This duplicates quite a bit of code. Once starting Pinnacle without xwayland is supported normally (see #222), the two `start_config` functions can probably be merged into a single, more generic one to get rid of this.

Follow up from #204.

**Comment by Ottatop** [comment]
After some refactoring, I think it's just cleaner to not have `start_config` be able to start arbitrary closures. The `no_config` option and starting a config separately seems to work well enough and doesn't require us to introduce any more complexity.
