### ISSUE TITLE
Pinnacle won't use generated config.

### ISSUE THREAD

**Issue by lidgnulinux** [pinnacle-comp/pinnacle#270]
Hello, I managed to build pinnacle and generated config at ~/.config/pinnacle. Somehow pinnacle won't use the config. I press super + enter and no terminal show up. I'm using foot terminal (I change alacritty to foot in config). 

I'm using latest master. Thanks.

**Comment by lidgnulinux** [comment]
I'm using lua so, this issue #263 somehow similar.

**Comment by Ottatop** [comment]
Can you upload your config as well as any logs in `~/.local/state/pinnacle`?
